export default {
    email_placeholder :"Email",
    password_placeholder:"Contraseña",
    login_button:"Iniciar sesión",
    register_link:"Registrarse",
    forgot_password_link:"Se te olvidó tu contraseña?",
    facebook_login_button:'Inicio de sesión en Facebook.',
    password_blank_messege:'La contraseña no puede estar en blanco.',
    password_alphaNumeric_check:'La contraseña debe tener al menos 1 carácter alfanumérico y longitud 8-15.',
    password_complexity_check:'La contraseña debe ser al menos 1 letra minúscula, 1 letra mayúscula, 1 dígito, 1 carácter especial y 6-10 de longitud.',
    valid_email_check:'Por favor ingrese un correo electrónico válido.',
    facebook_login_error:'Ya tienes una cuenta con esta dirección de correo electrónico. Por favor inicie sesión con su correo electrónico y contraseña.',
    forgot_password_success_messege:'Un enlace de restablecimiento de contraseña ha sido enviado a su correo electrónico, compruebe y restablezca su nueva contraseña.',
    facebook_login_auth_error:'Error de inicio de sesión de Facebook:',
    static_notification_title:'Notificación Segutaxi',
    refferal_code_validation_modal:'Validar su código de referencia...',
    refferal_id_not_match_error:'Este no es un ID de referencia válido.',
    registration_title:'Registro',
    first_name_placeholder:'Nombre',
    first_name_blank_error:"Por favor, introduzca su nombre.",
    last_name_placeholder:'Apellido',
    last_name_blank_error:'Por favor ingrese su apellido.',
    mobile_no_placeholder:'Número de teléfono móvil',
    mobile_no_blank_error:'Por favor, introduzca un número de móvil válido.',
    confrim_password_placeholder:'Confirmar contraseña',
    confrim_password_not_match_err:'Las contraseñas no coinciden',
    referral_id_placeholder:'ID de referencia (opcional)',
    register_button:'Regístrate ahora',
    email_exist_error:'La dirección de correo electrónico ya está en uso por otra cuenta.',
    Account_linking_error:'Error de enlace de cuenta',
    send_email_button:'Enviar correo electrónico',
    book_your_ride_menu:'Reserve su viaje',
    profile_setting_menu:'Perfil de usuario',
    my_wallet_menu:'Mi billetera',
    my_rides_menu:'Mis viajes',
    about_us_menu:'Acerca de nosotros',
    logout:'Cerrar sesión',
    photo_upload_action_sheet_title:'Elija un tipo de medio?',
    camera:'Cámara',
    galery:'Galeria',
    cancel:'Cancelar',
    yes:'si',
    network_request_failed:'Solicitud de red fallida',
    password_update_messege:'Tu contraseña se actualizó correctamente',
    delete_account_modal_title:'Confirmación',
    delete_account_modal_subtitle:'¿ Quieres eliminar tu cuenta ?',
    profile_page_title:'Mi perfil',
    my_wallet_title:'Saldo de mi billetera',
    profile_page_subtitle:'Detalles del perfil',
    location_lebel:'Ubicación',
    language_lebel:'Idioma',
    preffer_language:'Español',
    change_password_lebel:'Cambia la contraseña',
    delete_account_lebel:'Borrar cuenta',
    change_password_modal_title:'Cambiar la contraseña ?',
    old_password_placeholder:'Contraseña anterior',
    new_password_placeholder:'Nueva contraseña',
    old_password_validation_error:'Por favor ingrese su contraseña anterior',
    new_password_validation_error:'Por favor ingrese una nueva contraseña',
    update_button:'Actualizar ahora',
    update_profile_title:'Actualización del perfil',
    map_screen_where_input_text:'De donde ?',
    map_screen_drop_input_text:'Hasta donde ?',
    driver_finding_alert:'Buscando conductores para usted',
    no_driver_found_alert_title:'Alerta!',
    no_driver_found_alert_messege:'Lo sentimos, no se encontraron conductores en este momento. Vuelve a intentarlo más tarde.',
    no_driver_found_alert_OK_button:'OK',
    no_driver_found_alert_TRY_AGAIN_button:'Intenta otra vez',
    pickup_and_drop_location_blank_error:'Seleccionar lugar de recojo y destino',
    pickup_location_blank_error:'Seleccionar lugar de recojo',
    drop_location_blank_error:'Seleccionar ubicación de destino',
    car_type_blank_error:'Seleccione tipo de auto',
    congratulation:'Felicidades!',
    refferal_bonus_messege_text:'Cantidad de bonificación de referencia -',
    map_screen_title:'SeguTaxi',
    cab_selection_title:'Elige el tipo de vehículo',
    cab_selection_subtitle:'Toque para seleccionar el tipo de automóvil y reservar ahora',
    not_available:'No disponible',
    book_now_button:'Reservar ahora',
    contact_details:'Detalles de contacto',
    phone:'Teléfono',
    my_wallet_tile:'Mi billetera',
    wallet_ballance:'Saldo de billetera',
    add_money:'Agregar dinero',
    transaction_history_title:'Historial de transacciones de billetera',
    successfully:'Exitosamente',
    form_wallet:'Billetera de forma',
    Transaction_Id :'ID de transacción ',
    ride_list_title:'Mis viajes',
    no_car_assign_text:'Vehículo no asignado',
    not_found_text:'No encontrado',
    ride_details_page_title:'Detalles de mis viajes',
    you_rated_text:'Usted calificó',
    car_no_not_found:'Matricula de vehículo no encontrado',
    track_now_button:'Seguir ahora',
    bill_details_title:'Detalles de pago',
    your_trip:'Tu viaje',
    discount:'Descuento',
    promo_apply:'(Promoción aplica)',
    grand_total:'Gran total',
    payment_status:'Estado de pago',
    paynow_button:'Pagar ahora',
    call_driver:'Llamar al conductor',
    booked_cab_title:'Vehículo reservado',
    you_selected:'Usted seleccionó -',
    otp:'OTP :',
    driver_assign_messege:'El conductor se asignará pronto..',
    cancel_ride:'Cancelar viaje',
    rider_cancel_text:'Cancelar viaje',
    cancel_messege1:'Su viaje con Id. de reserva',
    cancel_messege2:'ha sido cancelado con éxito',
    dont_cancel_text:'No cancelar',
    cancel_reason_modal_title:'¿Cuál es la razón de cancelación?',
    chat_title:'Chat',
    send_button_text:'Enviar',
    chat_input_title:'Escribe algo lindo...',
    chat_not_found:'No se encontró el historial de chat',
    card_payment_blank_error:'Por favor complete todos los detalles correctamente.',
    payment_amound_error:'El monto del pago es demasiado pequeño.',
    invalid_card_details_error:'La tarjeta no es valida.',
    success_payment:'Pago exitoso',
    confrimation:'Confirmación',
    payment_alert:'¿Quieres borrar tu tarjeta? ',
    please_wait:'Por favor espera...',
    enterCVV:'Por favor, introduzca su CVV',
    your_promo:'Su promo',
    promo_exp:'¡Lo sentimos! El código de promoción y el límite de uso de la promoción caducaron.',
    promo_limit:'¡Lo sentimos! Límite de uso promocional sobre.',
    promo_eligiblity:'LO SIENTO! No eres elegible para esta promoción.',
    payment:'Pago',
    bill_details:'Detalles de factura',
    apply_promo:'Aplicar promoción',
    your_fare:'Su tarifa',
    promo_discount:'Descuento promocional',
    wallet_discount:'Descuento de billetera',
    payable_ammount:'Cantidad a pagar',
    use_wallet_balance:'Usar Wallet Cash (Su saldo - ',
    pay_cash:'Pagar en efectivo',
    pay_card:'Pagar con tarjeta',
    proceed_pay:'Proceda a pagar',
    save_card:'Tarjetas guardadas',
    thanks:'Gracias por calificar',
    skip:'Omitir',
    receipt:'Recibo',
    rate_ride:'Por favor califique su viaje',
    err:'Error!',
    route_not_found:'No se puede encontrar ninguna ruta.',
    sorry:'Lo siento',
    multipleBooking:'SeguTaxi actualmente no admite múltiples reservas.',
    driver_not_found:'No podemos asignar un conductor en este momento. Contactar al administrador !!',
    new_booking_request_push_notification:'Tiene una nueva solicitud de reserva',
    fare_details:'Detalles de tarifas',
    base_fare:'Tarifa base',
    convenience_free:'Tarifa extra',
    total_fare:'Tarifa total',
    inclusive_tax:'(Incluye todos los impuestos)',
    nb:'N.B .: Su tarifa se incrementará si cambia la ruta y el destino',
    confrim_booking:'Reserva confirmada',
    estimate_fare_text:'Esta es solo su tarifa estimada',
    done:'Hecho',
    notification_headerText:'Notificación',
    notification_not_found:'No se encontró ninguna notificación.',
    track_cab:'Rastrea tu vehículo',
    location_permission:'Rastrea tu vehículo',
    ask_me_later:'Pregúntame luego',
    min_order_value:'Valor de pedido mínimo-',
    add_money_tile:'Agregar dinero',
    addMoneyTextInputPlaceholder:'Agregar cantidad ($)',
    transactionFaildMsg:'Transacción fallida',
    payWithCard:'Pagar con tarjeta',
    CardPaymentAmount:'Pagar con tarjeta',
    CashPaymentAmount:'Pagar en efectivo',
    WalletPayment:'Pagar con billetera',
    pay_mode:'Modo de pago',
    Balance:'Balance Segutaxi',
    android_channel: 'Notificaciones SeguTaxi'
}
